### ISSUE TITLE
Request for test module

### ISSUE THREAD

**Issue by sriharshavv** [magic282/NQG#2]
Hi,
Firstly thanks for the code and instruction
I have trained the model following the given instruction but I am unable to test it on real data.

If you can give me instructions on how to test my trained model (i.e, taking a paragraph(source), pos, ner,bio,Case tags) and generate a question as output it would be very help ful.

Thanks

**Comment by magic282** [comment]
Already updated.

**Comment by suresh96458** [comment]
@sriharshavv  where you able to provide your custom data and test the model?

@magic282 it would be helpfull if you could provide the instructions for the same if it has been updated

**Comment by cddpeter** [comment]
I have the same question for how to pre-preocessing the data into the 5 features. I am wondering if you can give some instruction on this ? Thanks @magic282

**Comment by bhavikapanara** [comment]
Thanks @magic282 

Can you please help me understand how to get "BIO" pre-processed file for train/test dataset.

**Comment by bhavikapanara** [comment]
> Hi,
> Firstly thanks for the code and instruction
> I have trained the model following the given instruction but I am unable to test it on real data.
> 
> If you can give me instructions on how to test my trained model (i.e, taking a paragraph(source), pos, ner,bio,Case tags) and generate a question as output it would be very help ful.
> 
> Thanks

@sriharshavv 
Do you know what is "bio" pre-processed file?

Please guide me on how to generate "bio" file, if you know about it.

Thanks a lot
