### ISSUE TITLE
how to train this model with my own corpus

### ISSUE THREAD

**Issue by shizhediao** [magic282/NQG#3]
Hi, thanks for your great work!
I was wondering how to train this model with my own corpus

**Comment by fan8502** [comment]
I really want to inquire about the question, too! It will help me a lot, plzzzzz.

**Comment by lankokelly** [comment]
@shizhediao  Hi, I also confuse the question! 
I’m wondering that did you get the solution?
Hope you can give me some instructions

Thanks!
