### ISSUE TITLE
Testing own input

### ISSUE THREAD

**Issue by keerthana1512** [magic282/NQG#7]
I am done with training the model.Confused with how to generate questions for my own input. Cou;d you please help me with the file that has to be run?

**Comment by suresh96458** [comment]
I also have the same issue

**Comment by magic282** [comment]
Hi, please use NLP tools to label the input for POS tag, NER. Stanford CoreNLP or NLTK are both fine. The case feature means whether a word has uppercase letters.

**Comment by bhavikapanara** [comment]
Thanks @magic282 for sharing the code.

As you have directly given the preprocessed data, I am unable to generate a question for the custom text data.

Can you please share the preprocessed code that you have used to pre-process the data.

Thanks,
Bhavika

**Comment by ug911** [comment]
@keerthana1512 @suresh96458 @bhavikapanara - Were you able to generate questions on your own corpus?

@magic282 - Could you help here?

**Comment by theDyingofLight** [comment]
I have the same problem too
How could you set beam_size in the train.py and never use it? @magic282
