### ISSUE TITLE
Code for NQG++

### ISSUE THREAD

**Issue by flackbash** [magic282/NQG#9]
Would it be possible to provide the code or maybe some code snippets for the NQG++ architecture with shared embedding matrix and pre-trained word embeddings?
That would really be a great help!

**Comment by magic282** [comment]
Hi, we are no longer actively maintaining this repo. But you could checkout [this](https://github.com/magic282/NeuSum/blob/master/neusum_pt/neusum/Models.py#L41) as a reference. Thanks.

**Comment by flackbash** [comment]
Great, I'll check it out, thanks.
